import type { Metadata, Viewport } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { cn } from "@/utils/cn"
import { TRPCReactProvider } from "@/trpc/react"

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Budgie",
  //description: "Generated by create next app",
}

export const viewport: Viewport = {
  minimumScale: 1,
  initialScale: 1,
  width: "device-width",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "my-0 mx-auto max-w-screen-xl py-2 sm:py-0 font-sans antialiased")}>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  )
}
